### ISSUE TITLE
osgi-dining-hakkers sample broken with scalatest 2.2.3

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16703]
```
2.3.1 | Error installing boot features
java.lang.Exception: Could not start bundle mvn:org.scalatest/scalatest_2.11/2.2.3 in feature(s) exam-2.6.0: The bundle "org.scalatest_2.2.3 [72]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.tools.ant; version="0.0.0"
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:482)[40:org.apache.karaf.features.core:2.3.1]
    at org.apache.karaf.features.internal.FeaturesServiceImpl$2.run(FeaturesServiceImpl.java:1150)[40:org.apache.karaf.features.core:2.3.1]
Caused by: org.osgi.framework.BundleException: The bundle "org.scalatest_2.2.3 [72]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.tools.ant; version="0.0.0"
```

Reported to scalatest: https://github.com/scalatest/scalatest/issues/484

**Comment by 2m** [comment]
When adding `osgiDiningHakkersSampleMavenTest` back to the aggregate, project build should be [changed](https://github.com/akka/akka/blob/b37c2c0b29583889ca930b5a2b05dfd226de11ff/project/AkkaBuild.scala#L383-L392) so that it publishes M2 artifacts of dependencies only when testing and to a custom directory.

**Comment by drewhk** [comment]
Is this still broken? This is a rather old ticket.

**Comment by patriknw** [comment]
we have this comment in `AkkaBuild`: FIXME osgiDiningHakkersSampleMavenTest temporarily removed from aggregate due to #16703

**Comment by drewhk** [comment]
meh, OSGi

**Comment by 2m** [comment]
Hey Github, I said "does *not* fix "...

**Comment by raboof** [comment]
Was this fixed by https://github.com/akka/akka-samples/commit/7f09ebbe45d676d48e7895005c226ffdf3614852 ?

**Comment by 2m** [comment]
It is still the same. Just moved to another repo. I'll create an issue there (#16)
