### ISSUE TITLE
FAILED: SystemMessageDeliveryStressTest

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17170]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2279/consoleFull

    [info] - must guaranteed delivery and message ordering despite packet loss  *** FAILED *** (10 minutes, 6 seconds)
    [info]   java.lang.AssertionError: assertion failed: timeout (10 minutes) during expectMsg while waiting for 203
    [info]   at scala.Predef$.assert(Predef.scala:165)
    [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
    [info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:339)
    [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
    [info]   at 

Most likely a fluke though.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2540/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2952/consoleText

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1187/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3045/consoleFull

This looks like serious issue. Marking it as a bug. cc @drewhk

I noticed this in the logs:

    [ERROR] [10/21/2015 23:40:20.683] [SystemMessageDeliveryStressTest-akka.remote.default-remote-dispatcher-8] [akka.remote.Remoting] actor name [endpointWriter] is not unique!
akka.actor.InvalidActorNameException: actor name [endpointWriter] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130)
	at akka.actor.dungeon.Children$class.reserveChild(Children.scala:77)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:373)
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:215)
	at akka.actor.dungeon.Children$class.actorOf(Children.scala:38)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:373)
	at akka.remote.ReliableDeliverySupervisor.akka$remote$ReliableDeliverySupervisor$$createWriter(Endpoint.scala:389)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:338)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:188)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525)
	at akka.actor.ActorCell.invoke(ActorCell.scala:494)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


Note that the `InvalidActorNameException` also exists in the failure from 6 months ago.

**Comment by drewhk** [comment]
Ok, looking at it.

**Comment by patriknw** [comment]
The issue with `InvalidActorNameException: actor name [endpointWriter] is not unique` is probably fixed by https://github.com/akka/akka/pull/19178, where we introduced the `writerTerminated`. That was fixed in master and release-2.3. Therefore I will close this issue.

**Comment by bcwajapey** [comment]
Hi Patrik,

We are using Akka 2.4.1, but we still see this error. Can you please tell us what could be the issue here? Let me know if you need more info on this error.

2016-04-04 16:13:41.348/PDT ERROR [ClusterSystem-akka.actor.default-dispatcher-22] ClusterSystem-akka.remote.default-remote-dispatcher-33 akka.remote.Remoting [akka.remote.Remoting.71] actor name [endpointWriter] is not unique! 
akka.actor.InvalidActorNameException: actor name [endpointWriter] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130)
	at akka.actor.dungeon.Children$class.reserveChild(Children.scala:77)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:373) 
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:215)
	at akka.actor.dungeon.Children$class.actorOf(Children.scala:38)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:373) 
	at akka.remote.ReliableDeliverySupervisor.akka$remote$ReliableDeliverySupervisor$$createWriter(Endpoint.scala:389)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:338)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:188)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525) 
	at akka.actor.ActorCell.invoke(ActorCell.scala:494) 
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) 
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) 
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) 
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) 
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) 
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) 
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ktoso** [comment]
Please upgrade to 2.4.3 and verify there – there's a reason we keep releases binary compatible: so you can just upgrade to the latest version that has all fixes in it :wink:

**Comment by patriknw** [comment]
Yes, I think we have fixed something. Let us know the result.
