### ISSUE TITLE
Add support for websocket route testing to http-testkit

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17914]
This should allow:
 * writing a WS update request containing a mock client-side handler flow
 * asserting on the upgrade being successful
 * assert on the behavior of the supplied server-side handler flow

Right now everything needs to be done manually:

https://github.com/akka/akka/blob/release-2.3-dev/akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/WebsocketDirectivesSpec.scala#L16

**Comment by jrudolph** [comment]
Fixed in #18282.

**Comment by fommil** [comment]
sweet! We should test our ENSIME websockets endpoint with this. I still don't know if it works.
