### ISSUE TITLE
References to code samples are broken in akka-stream-and-http documentation

### ISSUE THREAD

**Issue by cppexpert** [akka/akka#18104]
References to code samples are broken in akka-stream-and-http documentation.

For example in http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/parameter-directives/parameters.html#parameters it renders

```
Required parameter
... includecode2:: ../../../../code/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala
snippet:	required-1
```

**Comment by ktoso** [comment]
Thanks for reporting and sorry for the trouble, we'll fix that soon!

// cc @sirthias @jrudolph

**Comment by cppexpert** [comment]
Guys, any progress on this ? It might be easy fix in some config I suspect.

**Comment by ktoso** [comment]
Not yet, sorry – vacation season struck our throughput, catching up with tickets now.

**Comment by ktoso** [comment]
Resolved by #18495 and listed missing docs: https://github.com/akka/akka/issues/18496 will work on them today.

**Comment by cppexpert** [comment]
Guys, it's still broken.

Sample page
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/parameter-directives/parameters.html#parameters

**Comment by ktoso** [comment]
Because there has not been a release, docs are generally published immutably according to their version number - fix will come in 1.1 (which is rather soon, no dates yet though)

**Comment by ktoso** [comment]
The fix here we could somewhat backport, however it would not be complete still, because of the missing things I found: https://github.com/akka/akka/issues/18496

// cc @rkuhn in case you think we should fix the some cases (it's a search-replace) and release 1.0 again. The above linked things though (the ticket) will still be missing

**Comment by rkuhn** [comment]
We’ll release 1.1 soon, don’t spend time on back-porting: streams are experimental for a reason.
