### ISSUE TITLE
HTTP client not properly handling connection failures

### ISSUE THREAD

**Issue by suiryc** [akka/akka#18311]
Using the examples given in the documentation, on an URL where nothing is listening (and thus triggering a connection failure right away - akka.stream.StreamTcpException), with akka 2.3.12 and akka-http 1.0.

With the [request-level API super pool](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/client-side/request-level.html#Flow-Based_Variant), trying a lot of requests in a short time (just do a loop of a thousands requests injected in the pool) freezes the pool after some time: sometimes after a few requests, sometimes after a few hundreds ones.
The same may happen with host-level pools.

With the [connection-level API](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/client-side/connection-level.html#Opening_HTTP_Connections), it appears resources created by the stream (mainly the actors) remain in the system and use (more and more) memory without ever being terminated (and reclaimed by GC).
Not an issue if you do only a few requests, but it you have a system running 24/24 for a long time, it may become one.

If pointing to a valid URL (properly listening - even if responding error codes -, and not forgetting to consume the response on the client side), everything goes fine: no pool frozen, and no remaining actors/memory used.

Is there something I can/must do when facing connection issues ? Or is this something to fix inside akka-http/akka-stream ?

**Comment by jrudolph** [comment]
To me it looks like a bug but it would be nice if you could provide us with a standalone reproducer that shows that something is broken inside of akka-http.

/cc @sirthias

**Comment by suiryc** [comment]
Some [gist code](https://gist.github.com/suiryc/72aa6212a174d9ece44d).

I tried to keep it simple.

When testing `sendPoolFlow`, as you can see, injecting a bunch of requests, which I believed should be buffered by the Source actor - up to 10000 - and processed when possible, first output:
```
[ERROR] [08/25/2015 20:16:09.300] [test-client-akka.actor.default-dispatcher-14] [ActorSystem(test-client)] Outgoing request stream error (akka.stream.StreamTcpException)
1: akka.stream.StreamTcpException: Connection failed.
...
65: akka.stream.StreamTcpException: Connection failed.
```
then nothing anymore. A second run goes up to 37, then again nothing anymore. Depending on the computer, it can freeze as soon as ~10 requests, and sometimes go to 100-200 requests.

I also just tried the `singleRequest` version (with `sendPoolFuture`): doing a limited number of requests is often OK. Going up to 32 at the same time (which is the default max-open-requests; beyond that requests are immediately failed) usually locks up: no response at all is received.

Then finally the connection-level test with `sendSingle`: all requests are performed (and of course fails), but if you fire up e.g. jvisualvm, do a GC to remove unnecessary used memory, and have a look at what remains, you should see ~25000 ActorCell/RepointableActorRef accounting for 90% of retained used memory. If pointing to a valid URL, nothing of this remains in memory at the end.

**Comment by jrudolph** [comment]
Thanks, @suiryc, this increases the chances a lot that we can determine what the problem is.

**Comment by ktoso** [comment]
I'll work on this today.

**Comment by ktoso** [comment]
So far I think the reason seems to be related to some racy behaviour in request messages to the SlotProcessor. The times I got it to get stuck I found the following in the logs:

```
[WARN] [11/17/2015 18:22:52.598] [ConnectionTest-akka.actor.default-dispatcher-17] [akka://ConnectionTest/user/SlotProcessor-3] unhandled message from Actor[akka://ConnectionTest/user/$a/flow-44226-0-actorPublisherSource#1363234051]: FromConnection(Request(16))
[WARN] [11/17/2015 18:22:52.598] [ConnectionTest-akka.actor.default-dispatcher-17] [akka://ConnectionTest/user/SlotProcessor-3] unhandled message from Actor[akka://ConnectionTest/user/$a/flow-44226-0-actorPublisherSource#1363234051]: FromConnection(Cancel)
^[[D
romise@298a582d,3)
```

**Comment by ktoso** [comment]
Added reference to @2m's reproducer PR https://github.com/akka/akka/pull/18476#event-490423070

**Comment by ktoso** [comment]
AFAIR I fixed this, in the linked merged PR.

**Comment by eirirlar** [comment]
I think this is still a problem in 2.4.14 with scala 2.12.1. Don't have time to put together a standalone example though.

**Comment by ktoso** [comment]
Please upgrade, the current version is 10.0.0. Reproducer or confirmation this still exists would help a lot, thanks.

**Comment by ktoso** [comment]
(Please open a new ticket if yet)

**Comment by hderms** [comment]
@ktoso I believe I'm getting a similar error. If I try to make an akka http request to a url with nothing listening behind it the stream becomes unresponsive

**Comment by xdev-developer** [comment]
Any updates on this?
akka-http version 10.0.5
pool freezes after making couple of requests.
Logs:
```21:15:42.915 [DEBUG] akka.http.impl.engine.client.PoolInterfaceActor - (Re-)starting host connection pool to localhost:8080
21:15:43.006 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
21:15:43.010 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
21:15:43.014 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
21:15:43.018 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
21:15:43.025 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://social-nw-client/system/IO-TCP/selectors/$a/1#1504330550]
21:15:43.031 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://social-nw-client/system/IO-TCP/selectors/$a/3#-1911079630]
21:15:43.031 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://social-nw-client/system/IO-TCP/selectors/$a/2#23254031]
21:15:43.031 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://social-nw-client/system/IO-TCP/selectors/$a/0#-474475047]
21:15:43.034 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:8080]
21:15:43.035 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:8080]
21:15:43.035 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:8080]
21:15:43.035 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:8080]
21:15:43.036 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:8080] due to java.net.ConnectException: Connection refused
21:15:43.036 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:8080] due to java.net.ConnectException: Connection refused
21:15:43.037 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:8080] due to java.net.ConnectException: Connection refused
21:15:43.037 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:8080] due to java.net.ConnectException: Connection refused
21:15:43.055 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
21:15:43.055 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:8080]
21:15:43.056 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:8080] due to java.net.ConnectException: Connection refused
21:16:05.566 [DEBUG] akka.io.TcpListener - New connection accepted
```

**Comment by jrudolph** [comment]
@xdev-developer could you please create a ticket on https://github.com/akka/akka-http? Please add information about how this can be reproduced.

**Comment by xdev-developer** [comment]
@jrudolph done.
https://github.com/akka/akka-http/issues/1006
