### ISSUE TITLE
No elements passed in the last 1 minute.

### ISSUE THREAD

**Issue by MasseGuillaume** [akka/akka#18982]
I get the following error every minute with akka-http
```
> [ERROR] [11/20/2015 16:57:04.937] [default-akka.actor.default-dispatcher-26] [ActorSystem(default)] Internal server error, sending 500 response
java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
    at akka.stream.impl.Timers$IdleBidi$$anon$4.onTimer(Timers.scala:142)
    at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:755)
    at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:745)
    at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:745)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:355)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:291)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.server.Directives._
import akka.stream.ActorMaterializer
 
object Main {
  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem()
    implicit val materializer = ActorMaterializer()

    val route =
      get {
        pathSingleSlash {
          complete("OK")
        }
      }
    Http().bindAndHandle(route, "0.0.0.0", 8080)
    ()
  }  
}
```

**Comment by ktoso** [comment]
We had a bug around idle timeouts in `2.0-M1`, I think this may be caused by it.
It is already fixed in a PR and will be fixed in M2  early next week ( https://github.com/akka/akka/pull/18973/files#diff-503164af09006abdb25eb9252d81deefR162 ) :-)

**Comment by ktoso** [comment]
I'll keep open to sanity check it was indeed that.

**Comment by hepin1989** [comment]
```
[Error][2015-11-25 21:14:13]: global payment notification handler not registered,could not handle notification :[PaymentNotification(Normal,{
  "game" : "xxjh",
  "channel" : "iap",
  "paymentType" : "DUMMY",
  "id" : "940184d8-b9a2-400c-8fdd-76b6c79d2727",
  "channelOrderId" : "channelOrderId1231222",
  "roleId" : 1,
  "productId" : "1",
  "orderPrice" : 1.11,
  "realPrice" : 11.11,
  "createTime" : "2015-11-25 21:13:14.0",
  "notifyTime" : "2015-11-25 21:14:12.728",
  "receiptData" : {
    "game" : "xxjh",
    "channel" : "iap",
    "id" : "940184d8-b9a2-400c-8fdd-76b6c79d2727",
    "channelOrderId" : "channelOrderId1231222",
    "roleId" : 123,
    "realPrice" : 11.11
  },
  "coreMD5" : "6ea693456f902aaac32b45a4a87fb078"
})]

   --> : akka.tcp://gear-runtime@127.0.0.1:2552/user/$a/globalNotificationManager
[Debug][2015-11-25 21:14:18]: Cancelling akka.stream.impl.MultiStreamOutputProcessor$SubstreamOutput@7ea831f8 (after: 5000 ms)
   --> : akka.tcp://gear-runtime@127.0.0.1:2552/user/$b/flow-3-2-prefixAndTail
[Error][2015-11-25 21:15:20]: Internal server error, sending 500 response

java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
	at akka.stream.impl.Timers$IdleBidi$$anon$4.onTimer(Timers.scala:142)
	at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:755)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:745)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:355)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:291)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525)
	at akka.actor.ActorCell.invoke(ActorCell.scala:494)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at qgame.engine.runtime.EngineExecutionContext$RunnableWrapper.exec(EngineExecutionContext.scala:63)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

   --> : PaymentClientPlugin(akka://gear-runtime)
```
another context here

**Comment by ktoso** [comment]
Verifying M2 against this now.

**Comment by ktoso** [comment]
Solved in M2 from what I can see (see above PR)

**Comment by ngbinh** [comment]
Still happens to me on M2.

```scala
10:12:04 ERROR [akka.actor.ActorSystemImpl(stargazer-service-system)] - Outgoing response stream error
java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
  at akka.stream.impl.Timers$IdleBidi$$anon$4.onTimer(Timers.scala:145) ~[akka-stream-experimental_2.11-2.0-M2.jar:na]
  at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:939) ~[akka-stream-experimental_2.11-2.0-M2.jar:na]
  at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:929) ~[akka-stream-experimental_2.11-2.0-M2.jar:na]
  at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:929) ~[akka-stream-experimental_2.11-2.0-M2.jar:na]
  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:357) ~[akka-stream-experimental_2.11-2.0-M2.jar:na]
  at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.1.jar:na]
  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:292) ~[akka-stream-experimental_2.11-2.0-M2.jar:na]
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.1.jar:na
```

You can see that I am using akka-http `2.0-M2` with akka `2.4.1`

**Comment by drewhk** [comment]
@ngbinh maybe because there are really no elements passing in the last minute?

**Comment by ktoso** [comment]
You're not showing the code where you see this happen @ngbinh, please do that when reporting such things :smile: 
I do think it's like @drewhk said – you're not passing elements, so idle timeout triggers...?

**Comment by drewhk** [comment]
The original bug was that idle timeout triggered even when the connection was not idle.

**Comment by ngbinh** [comment]
I am using it as the http server for our app. Of course when there is no user then there is no traffic. Does it mean we always have to send something every minute?

**Comment by drewhk** [comment]
If there is no user, then there should be no active connection though. This timeout should only trigger if there is an unclosed connection. Do you have a small reproducer to share?

**Comment by ngbinh** [comment]
ok, I will look into that.

**Comment by ngbinh** [comment]
note that I didn't see the problem on akka http '1.0'

**Comment by drewhk** [comment]
Because it didn't have an idle timeout, i.e. it happily leaked connections.

**Comment by ktoso** [comment]
Well sure, because it did not have timeouts – which was a missing feature.
Please share a reproducer, we do think the behaviour may be correct, just not what you're expecting.

**Comment by ngbinh** [comment]
Here are a simple example that can reproduce the behavior:

**Comment by drewhk** [comment]
@ngbinh have you used a browser to access the server? It might be that the browser keeps the connection open for a while? (@jrudolph @sirthias can that happen?)

**Comment by drewhk** [comment]
@ktoso this is not yet confirmed to be a bug though.

**Comment by ktoso** [comment]
Sure, ongoing discussion though so wanted to re-open to keep an eye on it.

**Comment by drewhk** [comment]
ok

**Comment by ngbinh** [comment]
yes, we need a browser to access it. Is there a way to log out the life-cycle of a connection?

**Comment by jrudolph** [comment]
From what I can say this is the idle timeout in action. Using a browser, it's likely that every connection will be closed by a timeout either from the client side or the server side. At least for HTTP the exception should be caught and converted into a log message with at most INFO level.

**Comment by drewhk** [comment]
Ok, I thought so. So this ticket is closed, we should open a new one for better log message.

**Comment by ktoso** [comment]
I agree. Closing and making it INFO in Http is this ticket now: https://github.com/akka/akka/issues/19058

**Comment by ngbinh** [comment]
:+1: thanks!

**Comment by jadlr** [comment]
I'm getting this in 2.0.3: 

```
2016-02-26 09:14:23,811 [TrialHarvester-akka.actor.default-dispatcher-75] DEBUG akka.actor.RepointableActorRef - Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.
akka.stream.impl.Timers$IdleTimeoutBidi$$anon$4.onTimer(Timers.scala:147)
akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1125)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1114)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1114)
akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:564)
akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:397)
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:547)
akka.actor.Actor$class.aroundReceive(Actor.scala:480)
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:493)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
akka.actor.ActorCell.invoke(ActorCell.scala:495)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

is this the same bug?

**Comment by ktoso** [comment]
Are you sure you are actually transmitting data over that connection?
This is an "idle timeout" so it may well be a valid situation that you got it.

// We highly recommend upgrading to Akka 2.4.2, please upgrade :)

**Comment by jadlr** [comment]
I did, I'll investigate further

**Comment by ktoso** [comment]
A reproducer would be great if you think it's a bug, thanks a lot!

**Comment by jadlr** [comment]
I rechecked and I get this error after every request completion. `Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.`

I am using akka 2.4.2 with akka-http 2.0.3 and slick 3.1.1. to grab some results from a db  and render them using @hseeberger s akka-http-json4s 1.5.2. I'll try to isolate the issue next week.

**Comment by ktoso** [comment]
Would you be able to upgrade to 2.4.2 of Akka Http along the way please? There's no reason to stay on 2.0.3 if you're on Akka 2.4 already :)

You say after request completion - what exactly do you mean – is the response written and then the connection kept alive? Could you share some sample code so we know which APIs and use case exactly we're talking about here? I'm still not sure if it's a valid idle timeout or if we bumped into a bug - more info is needed.

Thanks in advance :)

**Comment by jadlr** [comment]
Oh now I got it. I am so sorry! I thought you were referring to akka 2.4.2. I was so used to scroll down on http://akka.io/docs/ to check what the newest version of akka streams/http is that I didn't realize that it now says 'Older Versions'.

Please excuse my comments.

**Comment by ktoso** [comment]
No worries, we need to update the site to be more readable :) I'll do that,
thanks for pointing out it may be confusing ;)

**Comment by jrudolph** [comment]
AFAICS this is still an issue in 2.4.2 (even if it is less noisy than before):

```
backend [ERROR] [02/29/2016 14:48:57.938] [default-akka.actor.default-dispatcher-63] [akka://default/user/StreamSupervisor-0/flow-90-0-unknown-operation] Error in stage [recover]: No elements passed in the last 1 minute. (akka.http.impl.engine.HttpConnectionTimeoutException)
```

**Comment by ktoso** [comment]
Reopened to investigate again.

**Comment by jrudolph** [comment]
Probably we should reopen #19058 because it's only the logging issue which is still open.

**Comment by ktoso** [comment]
Thanks, in meetings these days

**Comment by drewhk** [comment]
@rleibman Do you actually send anything? The idle-timeout is 1 minute, so if you don't pass anything during that time it will close the connection. This is expected and normal. You should inject keepalive messages if you want to keep open idle connections.

**Comment by rleibman** [comment]
It's a websocket... I believe the RFC (https://tools.ietf.org/html/rfc6455) for websockets doesn't talk about idle times, once I connect I would have expected my connection to remain open, and I see no reason code in the RFC that states "session timed out". I was talking to @ktoso yesterday and he thought it was a good idea to be able to pass in the idle time out to the websocket directive (though I would still argue that it's against the RFC) or to have a different idle timeout for http connections than the one you have for websockets, Anyway, for my purposes I was able to globally change the timeout to 10 minutes and I reconnect after the server closes. This non standard behavior should probably be documented though.

**Comment by drewhk** [comment]
The RFC also does not talk about idle-timeouting ordinary HTTP connections. In spite of that it is a good practice to have idle timeouts, otherwise there is a risk of serious resource leaks. I rather protect my server from resource leaks and add app-level heartbeating instead of leaving connections open for arbitrary long time.

**Comment by ktoso** [comment]
@rleibman thinking out loud is not agreeing yet :-)
I see that a websocket may potentially be more long lived than a normal request/response and we don't have a good story about handling those separately in any way. The directive likely would resort to rather hacky things but is something to think about. 

Not having idle-timeouts is not an option, as @drewhk explains. Protecting the server takes priority.

**Comment by jrudolph** [comment]
Two things should probably be implemented here:
 * implement auto-pinging in the websocket implementation with an interval < the idle-timeout, this will
   * prevent the regular TCP-level idle-timeout from ever triggering
   * prevent that connections stay open where the peer host went away silently (won't answer with any ICMP messages any more)
 * implement another layer of optional idle-timeout directly in websocket which checks if any data frames have been exchanged in a given time-period

**Comment by Tvaroh** [comment]
I'm still getting it on 2.4.9.

**Comment by relgames** [comment]
Hi, I still see it in akka 2.4.10
I use akka-http to make http requests. Suddenly it stopped getting any responses from remote http services (remote services are up and responding fine) and I see a lot of
```
Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.
akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
```
in logs.

Not sure how to reproduce, it just happened; the applications had been running for ~24 hours.

**Comment by alcortaj** [comment]
Experiencing the same than @relgames on akka 2.4.11. The app seems to be fine making requests for over 12 hours. Despite the error "No elements passed in the last 1 minute." it's all over the logs I'm able to get all the responses just fine. However, at some point the app stops receiving responses. 

Note that in my case I only care about the response status and Im doing the following:

Http().singleRequest(request) map { case response: HttpResponse =>
          log.info(s"Got response ${response.status}")
          response.discardEntityBytes()
        }

**Comment by chauhraj** [comment]
I too got this issue in `akka-http 2.4.11`. I am not doing anything fancy but just calling `Source.single(request)` to akka http server. In my case, akka-stream is just a blackbox. 

Under what circumstances, will I see this error? 

However, when this exception happened, I also see another exception that occurred prior to this. 

`akka.stream.StreamTcpException:` Tcp command [Connect(<server-host-name>:<server-port>,None,List(),Some(10 seconds),true)] failed`

Can this exception manifest the TimeoutException? Strangely, StreamTcpException doesn't have any Stacktrace. Besides, I cannot reproduce any of the above errors. So, I am clueless when it may happen. I do not see any exceptions in my server logs.

**Comment by dancohensmith** [comment]
I am getting this with 2.4.12 it comes as debug logging but terminates the stream i have. I have an open ended connection between two microservices as i am streaming unidirectionally between them using Akka-http. It is casing the response entity stream to terminate in error:  I am watching the termination of the response stream:

6:52:50.114 [default-akka.actor.default-dispatcher-5] DEBUG akka.actor.RepointableActorRef - Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.
akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
akka.actor.Actor$class.aroundReceive(Actor.scala:484)
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
akka.actor.ActorCell.invoke(ActorCell.scala:495)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
16:52:50.121 [default-akka.actor.default-dispatcher-9] ERROR com.hsbc.dtc.de.pp.payments.TestHTTP - response process flow terminated badly
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Promise$class.failure(Promise.scala:104)
	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:153)
	at akka.stream.impl.fusing.GraphStages$TerminationWatcher$$anon$3.onUpstreamFailure(GraphStages.scala:134)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:733)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
	at akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
	at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
	... 13 common frames omitted

I am pretty sure i removed any timeouts : (application.conf)

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "DEBUG"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

}
akka.http {

  server {
    idle-timeout = infinite
  }
  client {
    idle-timeout = infinite
  }

  host-connection-pool {
    idle-timeout = infinite
  }


}

**Comment by ktoso** [comment]
Please first update to the latest version. Akka HTTP is now 10 0 2. If
problems persist please open a new ticket in the right repo. Akka/akka-http
