### ISSUE TITLE
Performance of Flow.flatMapMerge

### ISSUE THREAD

**Issue by hbf** [akka/akka#19299]
I've observed that `Flow.flatMapMerge` is slower than creating the involved streams explicitly and using a `Merge`.

I cooked this down to this:

```java
public static void main(String[] argv) throws Exception {
    final ActorSystem system = ActorSystem.create("testing");
    final Materializer mat = ActorMaterializer.create(system);

    long before = System.currentTimeMillis();
    final Source<Integer, BoxedUnit> source = true? // (*)
            Source.single(BoxedUnit.UNIT).flatMapMerge(1, __ -> createSource()) :
            createSource();

    Await.result(Source.fromGraph(source).toMat(Sink.ignore(), Keep.right()).run(mat), Inf());
    System.out.println("Took " + (System.currentTimeMillis()-before)/1000.0f);

    system.shutdown();
}

private static Source<Integer, BoxedUnit> createSource() {
    return Source.repeat(1).take(30000000);
}
```

Running time:

 * 21.2s (code above)
 * 2.9s (code above with `true` changed to `false` in line `*`)

Is this slow down expected (maybe because fusion cannot take place)? Is a workaround know? (In my use case, the stream's are not known at compile time.)

**Comment by ktoso** [comment]
Thanks for reporting @hbf!
We've not yet benchmarked that one, would you be able to help us out to get started on optimisations there by implementing a benchmark (using JMH), in akka-bench-jmh-dev? Here's an example benchmark: https://github.com/akka/akka/blob/release-2.3-dev/akka-bench-jmh-dev/src/main/scala/akka/stream/GraphBuilderBenchmark.scala

// here's a read-me how to run those: https://github.com/akka/akka/tree/release-2.3-dev/akka-bench-jmh
// it's using: https://github.com/ktoso/sbt-jmh

Thanks for the help in advance!

**Comment by hbf** [comment]
Sure. Have a a look here and let me know what you think: https://github.com/akka/akka/pull/19308

**Comment by hbf** [comment]
@ktoso Would you have a guess what needs to be done to make this faster? I'm not acquainted with Akka internals but maybe I'd be happy to spend some time trying to improve this. (Note: a quick look showed that the `flatMapMerge`-version generates about 2-3 times more churn, in particular `AsyncInput` instances.)

**Comment by ktoso** [comment]
I'd have do the same as anyone trying to optimise this, fire up a profiler and track hot-paths :)
This is not my priority this week, so any help would be appreciated :)

**Comment by hbf** [comment]
I took a quick look and gathered some material but haven't gotten deep enough into the implementation to see how this can be improved. Here's what I got:

The version using `flatMapMerge()` has significantly more memory pressure: 563.60 MB/s versus 31.79 MB/s.

The top objects created (over 30s) are:
  * `akka.stream.impl.fusing.ActorGraphInterpreter$AsyncInput`: 5.04 GB, 30% of pressure
  * `java.util.concurrent.ConcurrentLinkedQueue$Node`: 3.65 GB, 22% of pressure
  * `akka.dispatch.Envelope`: 3.54 GB, 21% of pressure
  * `akka.actor.Actor$$anonfun$aroundReceive$1`: 1.9 GB, 12% of pressure

I observed that most Akka dispatcher threads are "idling" in `ForkJoinPool.scan` and therefore ran the test with a single-threaded dispatcher to generate a [flame graph](https://gist.github.com/hbf/6bcbdfd1ac04ae09dd66).

Hope this helps further.

**Comment by agolubev** [comment]
Will take a look into this. Hope will find something interesting.

**Comment by jrudolph** [comment]
@hbf all the top things relate to extra messages sent.

I'm guessing a bit here since I'm not intricately familiar with the internals of fusing. The question is how dynamic subgraphs are materialized. IIUC for each dynamic subgraph a new `GraphInterpreter` is created wrapped inside a `GraphInterpreterShell` so that it can run in the same Actor as the original graph. However, communication between the original graph and the dynamic graph still communicate through messages (to `self`). This would pretty nicely explain the 10x performance penalty.

So, it seems that sub-stream fusing currently only optimizes the creation overhead (no new actors created per substream) but doesn't optimize the runtime overhead (inter-stream communication through messages) yet.

**Comment by drewhk** [comment]
@jrudolph is right, substreams are still dispatched asynchronously, but within the same actor. This is still much better than it was before fusing though, and the actual overhead of enqueueing and then immediately dequeueing in the actor (due to the `throughput` setting on the dispatcher) is not as high as actually passing between different actors. You still pay though materialization costs (just as before) and the envelope cost of individual messages (just as before).

Of course it is a nice optimization potential to avoid the actor messaging here, and it is not even particularly hard to do: 
 - GraphInterpreter should store an extra reference to an `Any` that can encode the "execution environment"
 - This context field should be simply set to be the ActorRef of the actor in ActorGraphInterpreter
 - AsyncCallback should retain a reference to this context object when it is created
 - on the call of `invoke()` check if the current interpreter's context (reading from `GraphInterpreter.currentInterpreter()`) equals the context assigned with this AsyncCallback instance. If it is, then proceed with calling the encapsulated callback directly

**Comment by drewhk** [comment]
@agolubev this is not particularly hard, so if you want to take a stab on it, then you can try the method I outlined above.

**Comment by jrudolph** [comment]
> This is still much better than it was before fusing though, and the actual overhead of enqueueing and then immediately dequeueing in the actor (due to the throughput setting on the dispatcher) is not as high as actually passing between different actors.

Has someone measured that? I agree, sending to self is a little faster but a big cost is the extra wrapping, the cost of the additional dispatches at `ActorRef.send` and in the dispatcher itself, and the overhead of dispatching through a `ConcurrentLinkedQueue`.

> If it is, then proceed with calling the encapsulated callback directly

Is that safe against stack overflows? I think you may need another queue/trampolining layer in the ActorGraphInterpreter to transfer signals between different GraphInterpreters.

**Comment by drewhk** [comment]
> Has someone measured that? I agree, sending to self is a little faster but a big cost is the extra wrapping, the cost of the additional dispatches at ActorRef.send and in the dispatcher itself, and the overhead of dispatching through a ConcurrentLinkedQueue.

Yes, implicitly I did back then. The dispatch is not as relevant if the actor is still executing, given if it has more rounds from the `throughput` limit, but of course you pay for all the queueing and the associated CAS and whatnot going in there. This is why what I proposed can improve this a lot (this is not a new idea just had no time to tinker with it).

> Is that safe against stack overflows? I think you may need another queue/trampolining layer in the ActorGraphInterpreter to transfer signals between different GraphInterpreters.

It is safe in basically all of the relevant cases. The current interpreters are strictly event based as they have an internal queue which they drain from. In this case, an async callback in almost all the cases either just changes the state of a stage (which is then a leaf of invokations), or calls to one of the stage methods push/pull etc. These just enqueue a message in the internal queue, so callback-wise, this would still be a leaf invokation. I.e. just an execution of an async callbacks callback endpoint does not start executing the interpreter queue. I might be missing something there though, but I don't think this is super hard to solve especially that there is a suspend/resume support in the actor itself to untangle such cycles if they ever happen.

**Comment by jrudolph** [comment]
Ah, I see. So, it should be possible to use the existing per-interpreter queues directly. You only need to make sure to actually run the other interpreter after you added the event.

**Comment by agolubev** [comment]
@drewhk sounds easy enough. Let me try.

**Comment by agolubev** [comment]
Now struggling with Stack overflow exception so need to find out how to interrupt the process within eventLimit

**Comment by drewhk** [comment]
That does not sound OK to me. There shouldn't be a deep stack in the first place, so the logic needs to be changed then. Can you share with us the code that you have so we can see how to avoid the cycle?

**Comment by agolubev** [comment]
here is patch of my changes [https://gist.github.com/agolubev/b328829ee33cd6855b58#file-19299_stack_overflow-diff](url) I run Test2 to have StackOverflow.

**Comment by agolubev** [comment]
Here is my changes: https://gist.github.com/agolubev/b328829ee33cd6855b58 I run Test2 to get StackOverflow
it looks like:
```
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:466)
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$2.apply(ActorGraphInterpreter.scala:324)
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$2.apply(ActorGraphInterpreter.scala:324)
	at akka.stream.stage.GraphStageLogic$$anon$2.invoke(GraphStage.scala:879)
	at akka.stream.impl.fusing.SubSink.pullSubstream(StreamOfStreams.scala:397)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.pull(GraphStage.scala:1009)
	at akka.stream.impl.fusing.FlattenMerge$$anon$4.akka$stream$impl$fusing$FlattenMerge$$anon$$pushOut(StreamOfStreams.scala:47)
	at akka.stream.impl.fusing.FlattenMerge$$anon$4$$anon$5.onPull(StreamOfStreams.scala:69)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:595)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:535)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:451)
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$2.apply(ActorGraphInterpreter.scala:324)
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$2.apply(ActorGraphInterpreter.scala:324)
	at akka.stream.stage.GraphStageLogic$$anon$2.invoke(GraphStage.scala:879)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet$$anonfun$4.apply(GraphStage.scala:986)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet$$anonfun$4.apply(GraphStage.scala:986)
	at akka.stream.impl.fusing.SubSink$$anon$2.onPush(StreamOfStreams.scala:413)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:577)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:535)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:451)
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$2.apply(ActorGraphInterpreter.scala:324)
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$2.apply(ActorGraphInterpreter.scala:324)
	at akka.stream.stage.GraphStageLogic$$anon$2.invoke(GraphStage.scala:879)
	at akka.stream.impl.fusing.SubSink.pullSubstream(StreamOfStreams.scala:397)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.pull(GraphStage.scala:1009)
	at akka.stream.impl.fusing.FlattenMerge$$anon$4.akka$stream$impl$fusing$FlattenMerge$$anon$$pushOut(StreamOfStreams.scala:47)
	at akka.stream.impl.fusing.FlattenMerge$$anon$4$$anon$5.onPull(StreamOfStreams.scala:69)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:595)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:535)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:451)
```

**Comment by drewhk** [comment]
You cannot put the `runBatch()` method in the sync callback. It seems like some minor indirection is still needed. One simple option is to check if there are any executable interpreters left after the previous runBatch() finished and the eventLimit has not been exhausted, and then call runBatch on the next one. But I am not yet sure what is the cleanest solution, I will need to look at the code a bit more. Also @rkuhn changed a bit how things work with the InterpreterShells and I am not 100% up to date with those.

**Comment by jrudolph** [comment]
Here's a quick try I had at it: https://github.com/spray/akka/commit/cb6b295330521280f9b062be674cbd4f1b2179ae. It tries to keep all changes local to the ActorGraphInterpreter since this is the point where the coordination needs to happen. I guess there are better solutions than introducing another ThreadLocal.

**Comment by agolubev** [comment]
Yeah, it fails tests exactly with the same reason as mine try: Cannot pull/push port twice.
As current implementations of async call believes all previous push/pulls already done for existing connection

**Comment by agolubev** [comment]
here is updated version https://github.com/agolubev/akka/commit/ccac3ea3b30336f29f1703fc9e291e5070c5afc1 work in progress, though.
7 tests failing now. Majority about not completed stages like: ```java.lang.AssertionError: assertion failed: expected no StreamSupervisor children, but got [Actor[akka://FlowSplitWhenSpec/user/StreamSupervisor-2/flow-29-0-unknown-operation#772494425]]```

**Comment by drewhk** [comment]
Those failures mean that the actor running the stages were not stopped. Either because a stage was not stopped, or the logic to stop the actor is no longer working properly.

**Comment by jrudolph** [comment]
> As current implementations of async call believes all previous push/pulls already done for existing connection

I see, so these are probably legitimate bugs / race-conditions that are uncovered with this change for some reason.

The problem with your current solution is that it still runs the callbacks on the stack. The only thing that currently prevents a StackOverflowException is that the GraphInterpreter keeps the `remainingEvents` in a variable that is shared by many execution loops on the same stack (i.e. the effect of your `runBatch` -> `tryBatch` change). So, the necessary stack space with your change is proportional to the `eventLimit` while it is constant for regular GraphInterpreter execution (where the `eventLimit` regulates fairness and not stack space).

This means that you can still run into StackOverflowExceptions if the `eventLimit` is too high for the stack size of the thread.

The `eventLimit` is defined as:

```
settings.maxInputBufferSize * (assembly.ins.length + assembly.outs.length)
```

which means that you will run into problems for big graphs or big buffers. To test this I added a static factor to that formula and I'm getting SOEs with your branch starting from a factor of ~ 15 for a stack size of 1MB.

I'd vote for introducing some trampolining to keep the stack size constant.

**Comment by drewhk** [comment]
> I'd vote for introducing some trampolining to keep the stack size constant.

+1

**Comment by jrudolph** [comment]
Btw. my sketch still has the opposite problem: it doesn't keep track of the eventLimit for all GraphInterpreterShells together so it doesn't provide any fairness if cross-shell calls are involved.

**Comment by drewhk** [comment]
I have not looked at any of the code from you guys yet, but @jrudolph can't you factor out the eventLimit variable to the shell instead, and reset its value on Resume events? Probably some round-robin scheduling of the interpreters will be necessary, with a smaller event limit each. Anyway I will look at this, but cannot do it today yet :(

**Comment by jrudolph** [comment]
> Probably some round-robin scheduling of the interpreters will be necessary, with a smaller event limit each.

Yes, you could probably return the remaining event limit and pass it to the next one. The question would be with which value to start.

Unfortunately, I won't be able to create a full-fledged PR this week. But @agolubev seems to be on a good way.

**Comment by agolubev** [comment]
> factor out the eventLimit variable to the shell instead, and reset its value on Resume events?

> I'd vote for introducing some trampolining to keep the stack size constant.

Ok, will continue with this

**Comment by agolubev** [comment]
with fix it's twice faster than was before. Still not the same performance as without substream.
For my laptop:
* 4s no substream
* 15s with fix
* 31s without fix

**Comment by jrudolph** [comment]
Yes, I have seen a similar 2x speedup with the fix. As for the remaining 3-4x slowdown for the dynamic case, I guess some slowdown is to be expected due to the dynamic nature of the setup. A "solution" for fixing this slowdown would be to rebuild the original interpreter. This would be a benefit in a case like this where there are only few, long-running dynamically generated (sub)graphs. In other cases, where there are lots of dynamic changes to the setup it may, on the other hand, introduce a further slowdown if you would have to rebuild the original graph frequently.

**Comment by drewhk** [comment]
What you mean by rebuilding it? You mean inlining the dynamic parts into the main interpreter? That is probably doable but it is probably not a simple endevour.

**Comment by drewhk** [comment]
I think first we should understand where the overhead comes from with the synchronous optimization.

**Comment by drewhk** [comment]
The performance difference might also come from the fact that the eventlimit is now shared between the two interpreters. Easy to check though by simply altering the event limit and see what happens. Be sure also to benchmark with fuzzing-mode off, because that adds a lot of overhead.

**Comment by agolubev** [comment]
> As for the remaining 3-4x slowdown for the dynamic case, I guess some slowdown is to be expected due to the dynamic nature of the setup.

Hm, will look into this

**Comment by jrudolph** [comment]
> What you mean by rebuilding it? You mean inlining the dynamic parts into the main interpreter? That is probably doable but it is probably not a simple endevour.

I agree.

> The performance difference might also come from the fact that the eventlimit is now shared between the two interpreters. Easy to check though by simply altering the event limit and see what happens. Be sure also to benchmark with fuzzing-mode off, because that adds a lot of overhead.

I just tried again and slowness in my version and in @agolubev's are actually not related :) In @agolubev's it's the newly introduced queue which is painfully slow. In my version was a bug which still sent around much more messages than necessary. After fixing this, the performance is about 1.7x slower than the simple version. This seems like a more realistic number.

After looking into the profiler the question was then rather how can the simple case be so fast? These are the top methods of the simple version:

```
  41.72%  perf-872.map        [.] Lakka/stream/impl/fusing/GraphInterpreter;::processEvent
  12.61%  perf-872.map        [.] Lakka/stream/impl/fusing/GraphInterpreterShell;::receive
```

Wow, pretty much all of the time is spent in one single method! It turned out that the graph was simple enough in this case that **all of the processing** was inlined into the interpreter! (I put the disassembler output here: https://gist.github.com/jrudolph/546181e26db26161777f)

This is, however, a very unlikely situation as in more realistic situations all the virtual calls in the interpreter will be megamorphic and introduce some overhead. So, as the base line of this 1.7x slowdown is too optimistic, the slowdown won't probably even be as big as seen here and probably more like 1.5x. We can hope to get runtimes like this:

 * simple case: 1x
 * flatMapMerge with an optimization like shown here: 1.5x
 * flatMapMerge current version: 5-10x

which sounds reasonable enough for me.

**Comment by agolubev** [comment]
Are we relying on some existing benchmarks? if not what should we write them?
For test in description there is FlatMapMergeBenchmark as for "simple case"

**Comment by agolubev** [comment]
@drewhk, for my implementation it's separate queue for async calls (that appears to be sync calls). Thinking about length of this queue - should it be taken from ActorMaterializerSettings.maxInputBufferSize?

**Comment by drewhk** [comment]
> I just tried again and slowness in my version and in @agolubev's are actually not related :) In @agolubev's it's the newly introduced queue which is painfully slow. In my version was a bug which still sent around much more messages than necessary. After fixing this, the performance is about 1.7x slower than the simple version. This seems like a more realistic number.

That is just totally awesome! Thanks for diving into this.

> Wow, pretty much all of the time is spent in one single method! It turned out that the graph was simple enough in this case that all of the processing was inlined into the interpreter! (I put the disassembler output here: https://gist.github.com/jrudolph/546181e26db26161777f)

That is funny :) 

> This is, however, a very unlikely situation as in more realistic situations all the virtual calls in the interpreter will be megamorphic and introduce some overhead. So, as the base line of this 1.7x slowdown is too optimistic, the slowdown won't probably even be as big as seen here and probably more like 1.5x.

Great, that is totally acceptable considering all the machinery that is involved here. Btw, I sometimes toy with the idea to do some bytecode rewriting to manually inline fused graphs just for the lulz (not sure if it is safely doable, but seems like a fun project).

@jrudolph where is your version?

**Comment by drewhk** [comment]
@agolubev for a queue you can use the FixedSizeBuffer (see here: https://github.com/akka/akka/pull/19703) that is backed by an array and should be faster than that mutable Queue. As for its size, given that you can always enqueue via the Actor mailbox, I don't think a  big queue is necessary. I would probably:

 - leave this queue as null until a new Interpreter is actually created in the shell to avoid paying the price of this queue if it is not even needed
 - have a size of 16 as a default, and let it to be overridden from config. It also probably makes sense to expose this as an Attribute, but it is not critical.

**Comment by jrudolph** [comment]
> Are we relying on some existing benchmarks?

I'm still using your code from above. A proper (JMH) benchmark would probably make sense...

> @jrudolph where is your version?

https://github.com/spray/akka/tree/w/19299-fix-streams-of-streams-performance

**Comment by agolubev** [comment]
>  it's the newly introduced queue which is painfully slow.

Yeah, when I being fixed tests it turned out that it's hard to stay in context and close the right GraphLogic in the right place. So the separate queue was introduced - will change it to array base buffer.

**Comment by akarnokd** [comment]
I've [benchmarked](https://github.com/akarnokd/akarnokd-misc/blob/master/src/jmh/java/hu/akarnokd/comparison/ReactiveStreamsImpls.java#L170) `flatMapMerge` with the latest 2.0.4 version and it still runs very slow with 1M elements. I get 0.06 ops/s.

We had a similar performance problem with our Rsc unbounded-in `flatMap` when followed by `observeOn` with almost the same throughput value. The problem was twofold: 1) `flatMap` was flooded by elements which yielded a lot of copy-on-write allocations in the inner tracking structure; 2) the cleanup part of the drain was traversing all sources looking for emptied ones, causing a lot of unnecessary work. 

However, a bounded `flatMap` shouldn't exhibit this drastic slowdown. I can't read Scala code but I'd verify if that `maxDepth` parameter is really considered or not.

**Comment by ktoso** [comment]
Thanks for sharing your findings :)
The change is not present on 2.0.4 though AFAIR – the most up to date version of streams is `2.4.3`, please try on that one (as it actually includes the PR for this issue). We don't backport all things to the 2.0.x series, it's just in "fixing only big bugs" mode.

**Comment by drewhk** [comment]
@akarnokd this fix is not in 2.0.4 that is legacy code. This has been fixed in 2.4.3

**Comment by akarnokd** [comment]
Thanks. I've rerun the benchmark with 2.4.3 but still getting around 0.07 ops/second.

**Comment by drewhk** [comment]
What is the code you have used?

**Comment by akarnokd** [comment]
```java

    @Setup
    public void setup() throws Exception {
        Config cfg = ConfigFactory.parseResources(ReactiveStreamsImpls.class, "/akka-streams.conf");
        actorSystem = ActorSystem.create("sys", cfg);

        materializer = ActorMaterializer.create(actorSystem);

        akRangeFlatMapJust = s -> 
                Source.range(1, times)
                .flatMapMerge(2, v -> Source.single(v))
                .runWith(Sink.asPublisher(AsPublisher.WITHOUT_FANOUT), materializer)
                .subscribe(s)
                ;
    }

    @Benchmark
    public void rangeFlatMapJust_akka(Blackhole bh) throws InterruptedException {
        LatchedRSObserver<Integer> lo = new LatchedRSObserver<>(bh);
        akRangeFlatMapJust.subscribe(lo);
        lo.latch.await();
    }
```

`akka-streams.conf` is both `reference.conf` from Akka and Akka Streams libs + version.conf. No changes there.

**Comment by drewhk** [comment]
This is the code we use: https://github.com/akka/akka/blob/master/akka-bench-jmh/src/main/scala/akka/stream/FlatMapMergeBenchmark.scala

Or have you mixed-in 3rd party publishers? This optimization only works across our fusable stages, it does not apply to other RS publishers if you try to flatten them. Nevertheless, if that is the case that is a problem we should look into.

**Comment by drewhk** [comment]
I see, so no 3rd party publishers. Interesting. Can you please open a new ticket with your reproducer? This is something else that this ticket was about but we need to investigate it.

**Comment by akarnokd** [comment]
This is just pure Akka-Streams:

```java
Source.range(1, times)
.flatMapMerge(2, v -> Source.single(v))
```

Your benchmark doesn't seem to run with a long source such as range(1, 1M) mapped to itself.

**Comment by drewhk** [comment]
I see, in your case the flattened sources are single element but there are many of them, the bench we have is less sources, but they are long. I think what you see there is the cost of materialization which is now not amortized since every Source.single has to suffer it.

**Comment by akarnokd** [comment]
Okay, I'll post a separate issue with the benchmark.

**Comment by drewhk** [comment]
Thanks!
