### ISSUE TITLE
quarantined node downed with auto-down-unreachable-after=off

### ISSUE THREAD

**Issue by michaelom** [akka/akka#20296]
akka 2.4.1

During what seems to be a network partition a cluster member downed a quarantined member:

```
[akka.tcp://SomeActorSystem@172.30.14.139:51000] with UID [-1507123525] irrecoverably failed. Quarantining address.

java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [-1 {}] ack: ACK[0, {}]
	at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:288)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:189)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was -1 but cumulative ACK is 0

Association to [akka.tcp://SomeActorSystem@172.30.14.139:51000] having UID [-1507123525] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.

Cluster Node [akka.tcp://SomeActorSystem@172.30.14.124:51000] - Marking node as TERMINATED [akka.tcp://AccountActorSystem@172.30.14.139:51000], due to quarantine

Cluster Node [akka.tcp://SomeActorSystem@172.30.14.124:51000] - Marking unreachable node [akka.tcp://AccountActorSystem@172.30.14.139:51000] as [Down]

Cluster Node [akka.tcp://SomeActorSystem@172.30.14.124:51000] - Leader can perform its duties again

Cluster Node [akka.tcp://SomeActorSystem@172.30.14.124:51000] - Leader is removing unreachable node [akka.tcp://SomeActorSystem@172.30.14.139:51000]

Member removed [akka.tcp://SomeActorSystem@172.30.14.139:51000]
```

Quarantined nodes seem to be downed even with auto downing disabled. That's not what I expected.

```  
def quarantined(node: UniqueAddress): Unit = {
    val localGossip = latestGossip
    if (localGossip.hasMember(node)) {
      val newReachability = latestGossip.overview.reachability.terminated(selfUniqueAddress, node)
      val newOverview = localGossip.overview copy (reachability = newReachability)
      val newGossip = localGossip copy (overview = newOverview)
      updateLatestGossip(newGossip)
      log.warning("Cluster Node [{}] - Marking node as TERMINATED [{}], due to quarantine",
        selfAddress, node.address)
      publish(latestGossip)
      downing(node.address)
    }
  }
```

**Comment by patriknw** [comment]
We have fixed something related to the system message acknowledgement buffer in Akka 2.4.3. Please try with that version. Please reopen if you see same with that version.

**Comment by WalkingGhost1975** [comment]
Please reopen:

This problem still occurs with Akka 2.4.12:
`Association to [akka.tcp://AnalyticsEventSourcingSystem@172.19.65.83:65024] having UID [2059192681] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.`
`Cluster Node [akka.tcp://AnalyticsEventSourcingSystem@172.19.65.79:65024] - Marking node as TERMINATED [akka.tcp://AnalyticsEventSourcingSystem@172.19.65.83:65024], due to quarantine.`
`Cluster Node [akka.tcp://AnalyticsEventSourcingSystem@172.19.65.79:65024] - Marking unreachable node [akka.tcp://AnalyticsEventSourcingSystem@172.19.65.83:65024] as [Down]`

We are not able to resolve cluster partition properly if quarantine automatically downs unreachable nodes.
This auto.downing of the other node by quarantine causes this node to become the oldest node in the cluster and therefore the ClusterSingletonManager starts additional singletons which are already running on the node that has been downed as described in http://doc.akka.io/docs/akka/2.4/scala/cluster-usage.html#automatic-vs-manual-downing-scala

Actually at that point in time the local node is already leaving the cluster, but still becomes the oldest node and is still starting singletons locally:
`18:14:04.207	Cluster Node [akka.tcp://AnalyticsEventSourcingSystem@172.19.65.79:65024] - Successfully shut down`
`18:14:04.225	Singleton manager starting singleton actor [akka://AnalyticsEventSourcingSystem/user/XXX-singleton/singleton]`
`18:14:04.231	ClusterSingletonManager state change [Younger -> Oldest]`
`18:14:04.232	Self removed, stopping ClusterSingletonManager`

**Comment by michaelom** [comment]
> We have fixed something related to the system message acknowledgement buffer in Akka 2.4.3. Please try with that version. Please reopen if you see same with that version.

@patriknw 
Code hasn't changed and apparently the issue still persists. Since I don't have permission to reopen this issue, could you do it, please.

**Comment by michaelom** [comment]
Also the code is not alined with the docs (well, it never is... ;-) ):

>>> If system messages cannot be delivered to a node it will be quarantined and then it cannot come back from unreachable. This can happen if [...]
Then the node needs to be moved to the down or removed states and the actor system of the quarantined node must be restarted before it can join the cluster again.
