### ISSUE TITLE
"Symbol 'type akka.pattern.AskSupport' is missing from the classpath" when compiling under jdk11

### ISSUE THREAD

**Issue by raboof** [akka/akka#26503]
When using jdk 11, restarting SBT might produce the following error when restarting without 'clean':

```
[info] Compiling 8 Scala sources to /home/aengelen/dev/akka/akka-actor/target/classes ...
[error] Symbol 'type akka.pattern.AskSupport' is missing from the classpath.
[error] This symbol is required by 'package akka.pattern.package'.
[error] Make sure that type AskSupport is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of akka.pattern.
[error] one error found
```

I seem to remember this was a problem that was fixed in some upstream project but not yet released (sbt? scalac?), but I don't remember the details... It seemed correlated to also having IntelliJ running, but I now saw it with no IntelliJ in sight.

**Comment by johanandren** [comment]
https://github.com/sbt/zinc/issues/622

**Comment by chbatey** [comment]
I get this very consistently if I have IntelliJ with SBT compilation along with a separate SBT shell.

**Comment by patriknw** [comment]
when this is fixed we should be able to remove the hack in the release script for `sbt deployRsync`

**Comment by patriknw** [comment]
Should be fixed with sbt 1.3.2 so I'm closing.

**Comment by raboof** [comment]
This problem is back - perhaps related to our recent update to sbt 1.3.10?

I haven't found a way to reliably reproduce it yet unfortunately

**Comment by patriknw** [comment]
I haven't seen in latest branch switches. Wonder if it is when switching between branches that have different sbt version?

**Comment by patriknw** [comment]
I have a way to reproduce it, and it doesn't involve changes of build files or switching branches.

```
master at 2a536d7065

sbt
akka > clean
akka > project akka-actor-tests
sbt:akka-actor-tests> test:compile

git revert 6a07c4f809
git revert 59c5071e52

sbt:akka-actor-tests> test:compile
```

**Comment by ignasi35** [comment]
I've edited the title.

I can reproduce the issue following @patriknw's steps above using JDK8u252 on a freshly cloned working copy.
